CREATE TABLE `monitored_urls` (
  `id` bigint unsigned AUTO_INCREMENT NOT NULL,
  `name` varchar(191) NOT NULL,
  `url` text NOT NULL,
  `normalized_url` text NOT NULL,
  `normalized_url_hash` char(64) NOT NULL,
  `enabled` boolean NOT NULL DEFAULT true,
  `next_check_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `check_claimed_at` timestamp NULL,
  `check_claimed_by` varchar(191),
  `latest_status` enum('UNKNOWN','OK','FAILING') NOT NULL DEFAULT 'UNKNOWN',
  `latest_failure_category` enum('DOWN','BLANK','ERROR_PAGE','VISUAL_BROKEN','BLOCKED'),
  `latest_summary` text,
  `latest_signals` json,
  `latest_http_status` int,
  `latest_final_url` text,
  `latest_duration_ms` int,
  `latest_checked_at` timestamp NULL,
  `latest_ai_classification` varchar(64),
  `latest_ai_confidence` int,
  `failure_started_at` timestamp NULL,
  `alert_sent_at` timestamp NULL,
  `recovered_at` timestamp NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT `monitored_urls_id` PRIMARY KEY(`id`),
  CONSTRAINT `monitored_urls_normalized_hash_unique` UNIQUE(`normalized_url_hash`)
);
